### ISSUE TITLE
completion with foo-abyss in neovim

### ISSUE THREAD

**Issue by FelipeLema** [victorze/foo#1]
Using deoplete, I can barely see the completion options:
![image](https://user-images.githubusercontent.com/1232306/57040364-2e710e00-6c2d-11e9-98e4-b45abe852b70.png)

**Comment by victorze** [comment]
I fixed it, thanks for reporting.

**Comment by FelipeLema** [comment]
fixed in https://github.com/victorze/foo/commit/fd29abb1daaa2644098d42ff060a651bbebde9cd and https://github.com/victorze/foo/commit/810168094b0166abc9eb33f9c139927a24b8d98f
