### ISSUE TITLE
visual selection with foo-hyper have same background and foreground colors 

### ISSUE THREAD

**Issue by FelipeLema** [victorze/foo#2]
Having the visual selection use the same colors for background and foreground makes the selected text unreadable.

In the image below, the cursor is on top of the `3` character.

![image](https://user-images.githubusercontent.com/1232306/57185257-06381800-6e96-11e9-9982-31aea3b4e087.png)

**Comment by victorze** [comment]
I fixed it.

**Comment by FelipeLema** [comment]
totally fixed. thanks

btw, [you can close issues in the commit message](https://github.blog/2013-01-22-closing-issues-via-commit-messages/)
